# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200)),
                ('click_number', models.IntegerField()),
                ('updated_at', models.DateField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
