# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonLink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='click_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='created_at',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='updated_at',
            field=models.BigIntegerField(),
        ),
    ]
