# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonLink', '0002_auto_20170908_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('updated_at', models.BigIntegerField()),
                ('created_at', models.BigIntegerField()),
            ],
        ),
    ]
