# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonLink', '0003_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='keywordContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_keyword', models.BigIntegerField()),
                ('id_content', models.BigIntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='keywordcontent',
            index=models.Index(fields=['id_content'], name='commonLink__id_cont_c716e4_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordcontent',
            index=models.Index(fields=['id_keyword'], name='commonLink__id_keyw_f39929_idx'),
        ),
    ]
