# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonLink', '0005_auto_20170909_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='keywordExtraLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_keyword_1', models.BigIntegerField()),
                ('id_keyword_2', models.BigIntegerField()),
                ('desc', models.CharField(default='normal', max_length=200)),
                ('updated_at', models.BigIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='keywordkeyword',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_keyword_parent', models.BigIntegerField()),
                ('id_keyword', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField(default=0)),
                ('created_at', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddIndex(
            model_name='keywordkeyword',
            index=models.Index(fields=['id_keyword_parent'], name='commonLink__id_keyw_111913_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordkeyword',
            index=models.Index(fields=['id_keyword'], name='commonLink__id_keyw_9a27b4_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordextralink',
            index=models.Index(fields=['id_keyword_1'], name='commonLink__id_keyw_0f16ec_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordextralink',
            index=models.Index(fields=['id_keyword_2'], name='commonLink__id_keyw_1659be_idx'),
        ),
    ]
