# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonLink', '0007_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='is_private',
            field=models.SmallIntegerField(default=0),
        ),
    ]
